// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetBlazorApp.DataLayer;

#nullable disable

namespace VetBlazorApp.Migrations
{
    [DbContext(typeof(VetClinicDbContext))]
    [Migration("20231228222950_ChangeToVaccineRegistryId")]
    partial class ChangeToVaccineRegistryId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VetBlazorApp.DataLayer.AnimalPassport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnimalPassports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 11,
                            Breed = "SomeBreed",
                            Gender = "Male",
                            Name = "A Dog"
                        });
                });

            modelBuilder.Entity("VetBlazorApp.DataLayer.Vaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalPassportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("VaccineRegistryId")
                        .HasColumnType("int");

                    b.Property<int>("VeterinarianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalPassportId");

                    b.HasIndex("VaccineRegistryId");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("Vaccinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalPassportId = 1,
                            Date = new DateTime(2023, 12, 28, 22, 29, 49, 732, DateTimeKind.Utc).AddTicks(9831),
                            VaccineRegistryId = 1,
                            VeterinarianId = 1
                        });
                });

            modelBuilder.Entity("VetBlazorApp.DataLayer.VaccineRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VaccineRegistries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiryDate = new DateTime(2024, 12, 28, 22, 29, 49, 732, DateTimeKind.Utc).AddTicks(9794),
                            SerialNumber = "12345",
                            VaccineName = "Vaccine1"
                        });
                });

            modelBuilder.Entity("VetBlazorApp.DataLayer.Veterinarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Veterinarians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Luke",
                            LastName = "Vader",
                            SocialNumber = "12345"
                        });
                });

            modelBuilder.Entity("VetBlazorApp.DataLayer.Vaccination", b =>
                {
                    b.HasOne("VetBlazorApp.DataLayer.AnimalPassport", "AnimalPassport")
                        .WithMany("Vaccinations")
                        .HasForeignKey("AnimalPassportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VetBlazorApp.DataLayer.VaccineRegistry", "VaccineRegistry")
                        .WithMany("Vaccinations")
                        .HasForeignKey("VaccineRegistryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VetBlazorApp.DataLayer.Veterinarian", "Veterinarian")
                        .WithMany("Vaccinations")
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalPassport");

                    b.Navigation("VaccineRegistry");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("VetBlazorApp.DataLayer.AnimalPassport", b =>
                {
                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("VetBlazorApp.DataLayer.VaccineRegistry", b =>
                {
                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("VetBlazorApp.DataLayer.Veterinarian", b =>
                {
                    b.Navigation("Vaccinations");
                });
#pragma warning restore 612, 618
        }
    }
}
